sudo: required
dist: trusty
language: c

script:
    - make $FLAGS
    - make check $FLAGS
    - make clean && git status --ignored --porcelain && test -z "$(git status --ignored --porcelain)"

matrix:
    include:
        - os: linux
          env: FLAGS="CC=gcc"

        - os: linux
          env: FLAGS="CC=gcc ARCH=i686"  # implies -m32 -march=i686
          addons:
              apt:
                  packages:
                      - gcc-multilib

notifications:
    email: false
