name: OpenLibm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - x64
          - x32
          - armv7
          - aarch64          
    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: make test
  
  buildwindows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with: 
        msystem: MINGW64
        install: make mingw-w64-x86_64-toolchain
    - run: make
    - run: make test
