name: OpenLibm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        arch:
          - x64
          - x32
          - armv7
          - aarch64          
    steps:
    - uses: actions/checkout@v2
    - run: make
    - run: make test
  
  buildwindows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with: 
        msystem: ${{matrix.sys}}
        install: make mingw-w64-${{matrix.env}}-toolchain
    - run: make
    - run: make test
