name: OpenLibm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        arch:
          - x64
          - x32
          - armv7
          - aarch64
          
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
    - name: make
      run: make
    - name: make test
      run: make test
